apiVersion: v1
kind: BuildConfig
metadata:
  name: sso-oracle
  labels:
    app: sso-oracle
spec:
  triggers:
    - type: Generic
      generic:
        secret: dd9709d12d8eb1ba
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/travisrogers05/rhsso-with-oracle-db'
      ref: master
  strategy:
    type: Source
    dockerStrategy:
      noCache: true
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: 'sso-oracle:1.0'
  resources: {}
  postCommit: {}
  nodeSelector: null